name: Renovate
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v31.63.2
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
